// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/extract": {
            "post": {
                "description": "Extracts detailed information about a GitHub repository including commits, milestones, and contributors.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "repository"
                ],
                "summary": "Extract repository information",
                "parameters": [
                    {
                        "description": "Repository extraction request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.ExtractRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/server.ExtractResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/server.ExtractResponse"
                        }
                    },
                    "422": {
                        "description": "Repository not eligible",
                        "schema": {
                            "$ref": "#/definitions/server.ExtractResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/server.ExtractResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Checks if the server is running and returns the number of cores.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ContributorDetail": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "blog": {
                    "type": "string"
                },
                "company": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "error": {
                    "description": "Error holds an error message when retrieval for this user failed",
                    "type": "string"
                },
                "followers": {
                    "type": "integer"
                },
                "following": {
                    "type": "integer"
                },
                "hireable": {
                    "type": "boolean"
                },
                "html_url": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "login": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "node_id": {
                    "type": "string"
                },
                "public_gists": {
                    "type": "integer"
                },
                "public_repos": {
                    "type": "integer"
                },
                "site_admin": {
                    "type": "boolean"
                },
                "twitter_username": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.RepositoryInfo": {
            "type": "object",
            "properties": {
                "commits": {
                    "type": "integer"
                },
                "contributors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ContributorDetail"
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "default_branch": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "forks": {
                    "type": "integer"
                },
                "has_issues": {
                    "type": "boolean"
                },
                "has_wiki": {
                    "type": "boolean"
                },
                "language": {
                    "type": "string"
                },
                "license": {
                    "type": "string"
                },
                "milestones": {
                    "type": "integer"
                },
                "open_issues": {
                    "type": "integer"
                },
                "owner": {
                    "type": "string"
                },
                "repo": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "stars": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "watchers": {
                    "type": "integer"
                }
            }
        },
        "server.ExtractRequest": {
            "type": "object",
            "properties": {
                "owner": {
                    "type": "string"
                },
                "repo": {
                    "type": "string"
                }
            }
        },
        "server.ExtractResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "repository": {
                    "$ref": "#/definitions/models.RepositoryInfo"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:6001",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GitHub Repository Extractor API",
	Description:      "This is a server to extract detailed information from GitHub repositories.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	// LeftDelim:        "{{",
	// RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
